Feature/homework1
kuzmychAndrew/MagicBall pull request #2
Opened 2022-02-15 17:07 UTC by kuzmychAndrew

2022-02-17 13:47 UTC, kuzmychAndrew commented
Yalantis HomeWork1

2022-02-18 08:36 UTC, sergey-prikhodko requested changes
замечания по мр незначительные, но заметил что в гит игноре не хватает системных файлов, например `.DS_Store`, а в `Podfile` нет версий зависимостей, нужно проставить

2022-02-18 08:36 UTC, sergey-prikhodko commented on .gitignore
> +#'Hello'
думаю можно убрать эту строку )

2022-02-18 08:36 UTC, sergey-prikhodko commented on New_8_Ball/Main/View/ViewController.swift
> +            getAnswer.leadingAnchor.constraint(equalTo: view.layoutMarginsGuide.leadingAnchor, constant: +80),
по всем констрейнтам ну нужны `+` там где они есть и `constant` это ж `CGFloat`, нужно добавить `.0` ко всем значениям которые могут быть с плавающей запятой, это считает хорошим тоном, там понятнее с чем имеешь дело, когда читаешь код

2022-02-18 08:36 UTC, sergey-prikhodko commented on New_8_Ball/Main/ViewModel/MainViewModel.swift.swift
> +    final func fetchAnswer(){
в таком случае лучше обозначить весь класс как `final`, тогда не нужно будет проставлять для каждой функции отдельно

2022-02-18 08:36 UTC, sergey-prikhodko commented on New_8_Ball/Services/JSONServices.swift
> +    final func getingJSONAnswer(completion : @escaping (Answers) ->()){
тут тоже

2022-02-18 08:36 UTC, sergey-prikhodko commented on New_8_Ball/Services/RealmServices.swift
> +    final func writingRealmAnswer(answer: String){
ну и здесь )

2022-02-18 08:36 UTC, sergey-prikhodko commented on New_8_Ball/Setting/View/SettingViewController.swift
> +    @objc final func save(sender: UIButton){
)

2022-02-18 21:37 UTC, sergey-prikhodko approved these changes

2022-02-21 12:50 UTC, closed without merging